DROP TABLE STRAFE;
DROP TABLE VORMERK;
DROP TABLE VERLEIH;
DROP TABLE LESER;
DROP TABLE BUECHER;

ALTER SESSION SET NLS_LANGUAGE = 'ENGLISH';
ALTER SESSION SET NLS_DATE_FORMAT = 'dd-MM-YY';


-- Creates | Nr. 1
CREATE TABLE Buecher (
    BUCH_NR NUMERIC NOT NULL,
    AUTOR VARCHAR(20),
    TITEL VARCHAR(40),
    G VARCHAR(20),
    LEIHFRIST NUMERIC,
    CONSTRAINT pk_Buecher PRIMARY KEY (BUCH_NR)
);

CREATE TABLE Leser (
    LESER_NR NUMERIC NOT NULL,
    NAME VARCHAR(20),
    WOHNORT VARCHAR(25),
    EINTRITTS date,
    CONSTRAINT pk_Leser PRIMARY KEY (LESER_NR)
);

CREATE TABLE Verleih (
    LESER_NR NUMERIC NOT NULL,
    BUCH_NR NUMERIC NOT NULL,
    AUSLEIHDA date,
    RUECKGABE date,
    CONSTRAINT pk_Verleih PRIMARY KEY (LESER_NR, BUCH_NR),
    CONSTRAINT fk_VerleihB FOREIGN KEY (BUCH_NR) REFERENCES Buecher(BUCH_NR),
    CONSTRAINT fk_VerleihL FOREIGN KEY (LESER_NR) REFERENCES Leser(LESER_NR)
);

CREATE TABLE Vormerk (
    LESER_NR NUMERIC NOT NULL,
    BUCH_NR NUMERIC NOT NULL,
    RESERVFUE date,
    CONSTRAINT pk_Vormerk PRIMARY KEY (LESER_NR, BUCH_NR),
    CONSTRAINT fk_VormerkB FOREIGN KEY (BUCH_NR) REFERENCES Buecher(BUCH_NR),
    CONSTRAINT fk_VormerkL FOREIGN KEY (LESER_NR) REFERENCES Leser(LESER_NR)
);

CREATE TABLE Strafe (
     LESER_NR NUMERIC NOT NULL,
     SPERRBIS date,
     GEBUEHR NUMERIC,
     CONSTRAINT pk_Strafe PRIMARY KEY (LESER_NR, SPERRBIS),
     CONSTRAINT fk_StrafeL FOREIGN KEY (LESER_NR) REFERENCES Leser(LESER_NR)
);

-- Nr. 2
select Buecher.BUCH_NR, Buecher.AUTOR, Buecher.TITEL, Vormerk.RESERVFUE as VORMERKDATUM from Vormerk, Buecher where Buecher.BUCH_NR = Vormerk.BUCH_NR;

-- Nr. 3
select Leser.LESER_NR, Leser.NAME, LESER.WOHNORT, count(V2.LESER_NR) as amountOFBooks from LESER LEFT JOIN Verleih V2 on Leser.LESER_NR = V2.LESER_NR group by Leser.LESER_NR, LESER.NAME, LESER.WOHNORT;

-- Nr. 4
select Leser.LESER_NR, Leser.NAME, Leser.WOHNORT, Buecher.TITEL, Verleih.RUECKGABE from Verleih, Buecher, Leser where Leser.LESER_NR = Verleih.LESER_NR and Verleih.BUCH_NR = Buecher.BUCH_NR and Buecher.AUTOR like 'Goe%';

-- Nr. 5
--select BUCH_NR, AUTOR, TITEL, RESERVFUE from BUECHER,

--Nr. 6
select Leser.LESER_NR, Leser.NAME, Leser.WOHNORT, Strafe.GEBUEHR from LESER, Strafe where NAME like 'Mayer' group by Leser.LESER_NR, Leser.NAME, Leser.WOHNORT, Strafe.GEBUEHR;