
# Übungen Group By
:icons: font

## Konfiguration

Schema: DEMO_HR +
ERD: https://student.cloud.htl-leonding.ac.at/oracle/dbman/assets/images/erd/hr_schema.pdf[] +
Wechsel des Schemas:

[source,sql]
----
alter session set current_schema=DEMO_HR
----

Alle Aufgaben sind jeweils mit **EINEM SQL-Statement** zu lösen!

## Anzahl Mitarbeiter pro Abteilung

Ermitteln Sie, wie viele `Employees` pro `Department` arbeiten. Sortieren
Sie das Ergebnis absteigend nach der Mitarbeiteranzahl, also die größte Abteilung an erster Stelle.

.Ergebnis:
[source,sql]
----
 Abteilung Anzahl Mitarbeiter
---------- ------------------
        50                 45
        80                 34
       100                  6
        30                  6
        60                  5
        90                  3
 ...
----

.Lösung:
[source,sql]
----
select e.department_id, count(e.employee_id) as "Anzahl Mitarbeiter"
from employees e
group by e.department_id
order by count(e.employee_id) desc

----

Ändern Sie das Statement so um, dass anstatt der Abteilungsnummer die Bezeichnung der Abteilung (`Department_Name`) ausgegeben wird. Verwenden Sie dazu eine Subquery.

.Ergebnis:
[source,sql]
----
Abteilung                      Anzahl Mitarbeiter
------------------------------ ------------------
Shipping                                       45
Sales                                          34
Finance                                         6
Purchasing                                      6
IT                                              5
...
----

.Lösung:
[source,sql]
----
select d.department_name, count(e.employee_id) as "Count"
from employees e, departments d
where e.department_id = d.department_id
group by d.department_name
order by count(e.employee_id) desc;
----

Wir interessieren uns jetzt nur für die größeren Abteilungen. Ändern Sie das Statement dahingehend ab, dass nur Abteilungen mit **mehr als 5 Mitarbeiter:innen** aufgelistet werden.

.Ergebnis:
[source,sql]
----
Abteilung                      Anzahl Mitarbeiter
------------------------------ ------------------
Shipping                                       45
Sales                                          34
Finance                                         6
Purchasing                                      6
----

.Lösung:
[source,sql]
----
select d.department_name, count(e.employee_id) as "Count"
from employees e, departments d
where e.department_id = d.department_id
group by d.department_name
having count(e.employee_id) > 5
order by count(e.employee_id) desc;
----


## Niederlassungen pro Land

Ermitteln Sie pro Land (`Country`) die Anzahl an Niederlassungen (`Locations`). +
Sortieren Sie das Ergebnis absteigend nach der Anzahl an Niederlassungen. Bei gleicher Anzahl wird aufsteigend nach dem Länderkürzel sortiert.

.Ergebnis:
[source,sql]
----
Land Anzahl Niederlassungen
---- ----------------------
US                        4
UK                        3
CA                        2
CH                        2
IT                        2
JP                        2
AU                        1
    ...
----

.Lösung:
[source,sql]
----
select c.country_id, count(l.location_id)
from countries c, locations l
where l.country_id = c.country_id
group by c.country_id
order by count(l.location_id) desc, c.country_id asc;
----



## Gehaltskosten pro Abteilung

Ermitteln Sie die Gehaltskosten, die pro Abteilung anfallen. Berücksichtigen Sie dazu die Spalte `Salary`. +
Es sollen nur Abteilungen mit Gehaltskosten ab 25.000 ausgegeben werden! +
Sortieren Sie das Ergebnis absteigend nach den Gehaltskosten. Geben Sie die Werte mit Tausenderpunkten und 2 Nachkommastellen aus!

.Ergebnis:
[source,sql]
----
AbteilungsNr Gehaltskost
------------ -----------
          80  304.500,00
          50  156.400,00
          90   58.000,00
         100   51.608,00
          60   28.800,00
----


TIP: Verwenden Sie in der Formatmaske `G` für die Tausender-Gruppierung (.), `D` für das Komma. Damit werden die aktullen Ländereinstellungen berücksichtigt.

.Lösung:
[source,sql]
----
select d.department_id, to_char(sum(e.salary), '999G999D99')
from departments d, employees e
where e.department_id = d.department_id
group by d.department_id
having sum(e.salary) >= 25000
order by sum(e.salary) desc;
----



### Gehaltskosten pro Abteilung und Job

Ändern Sie das vorige Statement so ab, dass die gesamten Gehaltskosten und die Durchschnittsgehälter **pro Abteilung und Job** ermittelt werden. +
Durchschnittsgehälter < 10.000 sollen nicht ausgegeben werden. +
Die Abteilung ist mit ihrer Bezeichnung auszugegeben. Lösen Sie dies mit Hilfe einer Subquery. +
Sortieren Sie das Ergebnis absteigend nach dem Durchschnittsgehalt, es soll also der am besten bezahlte Job an erster Stelle stehen.

.Ergebnis:
[source,sql]
----
Abteilung                      Job        Gehaltskosten Durchschnittsgehalt
------------------------------ ---------- ------------- -------------------
Executive                      AD_PRES      24.000,00     24.000,00
Executive                      AD_VP        34.000,00     17.000,00
Marketing                      MK_MAN       13.000,00     13.000,00
Sales                          SA_MAN       61.000,00     12.200,00
Finance                        FI_MGR       12.008,00     12.008,00
Accounting                     AC_MGR       12.008,00     12.008,00
Purchasing                     PU_MAN       11.000,00     11.000,00
Public Relations               PR_REP       10.000,00     10.000,00
----

.Lösung:
[source,sql]
----
-- falsch
select d.department_name, j.job_title, avg(e.salary) as "Durchschnittsgehalt", to_char(sum(e.salary) , '999G999D99') as "Gehaltskosten"
from departments d, employees e, jobs j
where e.department_id  = d.department_id
    and e.job_id  = j.job_id
group by d.department_name, j.job_title
having avg(e.salary) >= 10000
order by avg(e.salary) desc,
         d.department_name desc;
----


## Durchschnittsgehalt pro Abteilung exkl. Führungskräfte

Ermitteln Sie das Durchschnittsgehalt pro Abteilung. +
Beachten Sie dabei, dass Gehälter von Jobs, die die Bezeichnungen `Manager` oder `President` im `Job_Title` haben, nicht berücksichtigt werden. Ebenso sollen Mitarbeiter:innen ausgeschlossen werden, die keiner Abteilung zugeordnet sind. +
Durchschnittsgehälter unter 5.000 sollen nicht ausgegeben werden.

Die Verwendung von Joins ist hier nicht erlaubt. +
Sortieren Sie das Ergebnis absteigend nach dem Durchschnittsgehalt.


.Ergebnis:
[source,sql]
----
Abteilung Durchschnit
---------- -----------
        70   10.000,00
        80    8.396,55
       110    8.300,00
       100    7.920,00
        40    6.500,00
        20    6.000,00
        60    5.760,00
----

.Lösung:
[source,sql]
----
select e.department_id,
       avg(e.salary)
from employees e, jobs j
where e.job_id = j.job_id
and j.job_title <> 'Manager'
and j.job_title <> 'President'
and e.department_id is not null
group by e.department_id
having avg(e.salary) > 5000
order by avg(e.salary) desc
----

