-- 1.1
SELECT COUNT(*) AS ANZAHL, SPARTE FROM VERTRAG WHERE VENDE IS NULL GROUP BY SPARTE;


-- 1.2
SELECT VSUMME FROM VERTRAGSHISTORIE WHERE DATUM_VON < to_date('03.06.00', 'dd.mm.yy') AND VNR = 154 ORDER BY DATUM_VON DESC  FETCH FIRST ROW ONLY;


-- 1.3
SELECT VNR, VBEGINN FROM VERTRAG WHERE VENDE > to_date('00.9.97', 'dd.mm.yy') AND VENDE <= to_date('31.12.97', 'dd.mm.yy'); -- todo: replace vende with (VENDE / 4)           not null


-- 1.4
SELECT VNR FROM VERTRAG WHERE SPARTE LIKE 'P' AND (SELECT VNR FROM VERTARG WHERE to_date('31.12.02', 'dd.mm.yy')) = VNR;


-- 1.5
SELECT * FROM VERTRAG v FULL OUTER JOIN ZAHLUNG z ON v.VNR = z.VNR WHERE v.VENDE IS NULL AND to_number(z.ZDATUM, 'yy') != (to_number(z.ZDATUM, 'yy') - 1);

-- 1.6
SELECT v.VNR, vh.VSUMME FROM VERTRAG v FULL OUTER JOIN VERTRAGSHISTORIE vh ON v.VNR = vh.VNR WHERE v.VENDE IS NULL;


