= Mitschrift 
Stevan Vlajic
1.0.0, {docdate}:
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:


== 25-09-2023

=== Rechtsordnung

* Bundesgetzt 
** Gelten für ganz Österreich 
* Landesgesetz
** Gilt für einzelne Bundesländer

Nationalrat -> beschließt Gesetze

Bundesrat -> Kontrollinstanz 

=== Gewalten Österreichs
* Excekutive
** Polizei

* Judikative 
** richterliche Gewalten

* Legislative
** Gesetztgebende


==== EU Rechte

Die EU gibt: 

* Richtlinien -> Minimum von Beschluss muss umgestezt werden -> alles andere kann selbst beschlossen werden 

* Verordnungen -> DSGVO 

vor.

EU Regelungen stehen über unserem nationalem Recht 

=== Verfassungsgesetze 
* Brauchen eine Mehrheit in der Zustimmung bei der Beschließung und Aufhebung

=== Einfache Gesetze
* Beispiel:
** Niemanden umbrigen
** Niemanden verletzten
** Führerscheingesetz

* steht im ABGB -> Allgemeines bürgerliches Gesetzbuch
* seit 1812 

=== Verordnungen 
* Beispiele:
** Covid-Verordnung

=== Einzelfall Entscheidungen
* Persöhnliche Urteile, Bescheide, Beschlüsse


Alle Punkte müssen sich den oberen unterwerfen aber nichts darf umgedreht werden.


=== Öffentliches und Privates Recht

* Öffentliches Recht -> Staat auf einer Seite, Bürger auf der anderen Seite

* Privates Recht -> Bürger gegen Bürger

=== Zwingendes Recht und Nachgibiges Recht

* Zwingendes Recht:
** unabänderlich
** Beispiel: 
*** Unternehmensrecht
*** Mutterschutz 

* Nachgibiges Recht 
** Abänderbares Recht 


=== Fälle bestehen aus:

* Sachverhalt: was ist passiert 
** Zeugenaussagen

* Gesetzen:
** Für Normen zuständig -> subsumieren

=== Wie kommt man auf seine Rehcte
https://www.ris.bka.gv.at/

== 2023-02-10

* Rechtkraft
** Die Entscheidung gilt und ist fix -> Berufung nicht mehr nötig

=== Personenrecht
Betrifft Personen

* Natürliche Person:
** Alle Menschen 
* Juristische Person:
** GmBH's sind juristische Personen 
** Bund 
** Gemeinde

* Erbrecht:
** Ungeborene haben Rechte wenn sie geboren sind -> man bekommt rechte wenn man lebend geboren wird -> als Fötus erwirbt man Rechte -> Eltern sind immer die Erben 

* Wie lang ist man ein Mensch?
** Solange man nicht Hirntod ist, lebt man

Zwischen Geburt und Tod ist man Rechtsfähig -> man kann Rechte und Pflichten erwerben

* Wenn man geboren wird bekommt man alle Menschenrechte

=== Handlungsfähigkeit
Wer darf alles tun und lassen 

* Man unterscheidet beim alter 

Jeder darf sich alles um so viel Sachen kaufen, wie er will, solange die Eltern das erlauben.

** (0 - 7 Jahre) Jahre alt:
*** Altersüblichegeschäfte geringfügigen Umfangs darf man als handlungsunfähiges (0-7 Jahre) Kleinkind kaufen 
**** Glückspiel ist nicht erlaubt -> Rubellos

** (7 - 14) Jahre alt:
*** Man darf sich nicht verpflichten beispielsweise Handyverträge abschließen
*** Altersüblichegeschäfte geringfügigen Umfangs 

** (14 - 18) Jahre alt:
*** Man darf nicht alles ausgeben -> Lebenserhaltungskosten müssen erhalten bleiben 
*** Strafmündig -> Man wird selbst bestraft -> nicht mehr die Eltern -> keine Sekunde vor 14
*** Schadenersatzpflicht kommt hinzu -> kann auch vor 14 vorkommen
*** Religionsmündigkeit -> Man entscheidet selbstständig ohne Eltern  
*** Sexualmündigkeit -> Man darf mit gleichatrigen Schlafen und ältern ohne Obgergrenze schlafen
**** 13 und 16, 13 und 17 geht nicht 


=== Handlungsfähigkeit

Wie lang geht die Aufsichtspflicht?

* Die Aufsichtspflicht geht normalerweise bis 18 aber der Umfang ändert sich pro Kind und pro Alter


== 2023-09-10

* Elternhaften für Ihre Kinder, wenn sie hre Aufsichtspflichten schuldhaften verletzen
-> Beispiel ist daher nichtig -> Eltern müssen nichts zahlen


== Erwachsenenschutzrecht

Man braucht Erwachsenenschutz wenn man nicht mehr Klarkommt: Behindert, Dement, ...

=== Möglichkeiten:
* Vorsorgevollmacht: 
** Man legt fest wer für einen Verantwortlich ist, wenn man nicht mehr alleine Zurecht komme

* Vorsorgevollmachten: 
** Medizinische Vollmachten
** Betreuerische Vollmachten
** Finanzelle Vollmachten

Gilt ewig -> Man muss sich bewusst sein während man das schreiben ausfüllt

* 4 Arten
** Vorsorgevollmacht -> Geistig fit -> die gilt 
** Gewählter Verträter 
** Familie: Lenht die betroffene Person -> kommt die Familie zum Einsatz (entfernt auch)
** Gerichtliche Vertrer
*** Erwachsenenschutzvereine stellt Leute


== 2023-16-10

* Die Patientenverfügung
** Maschinen angeschlossen lassen wenn man Todkrank ist 

* Jusristische Person:
Ist ein Konstrukt -> eine GMbH -> ist Rechtsfähig

* Deliktsfähigkeit: Wann kann man selbst vor dem Richter stehen -> ab 14 Jahren -> Wann halte ich den Kopf hin
* Rechtfähigkeit -> fähigkeit rechte zu haben

=== Schuldrecht 

Wie schließt man Verträge:

* Mündlich 
* Schriftlich
* Faktisch durch tun -> Kauf beim Automaten

Wann sind Veträge Gültig

* Jeder kann Veträge schließen, der Geschäftsfähig ist ( > 18)
* Willenserklärungen -> Ohne Zwang -> Ohne List -> ohne Irrtum
* Muss Möglich sein nicht unmöglich
* Es muss erlaubt sein (Gesetzlich erlaubt)
* Gute Sitten -> Jemandem mit Lernschwäche etwas andrehen 

== 2023-23-10

BS (258-264)

=== Arten von Verträgen
* Leihvertrag: Kostet nichts -> kein Geld 
* Darhlehnsvertrag: Man bekommt etwas selber Art und Güte zurück
* Kreditvertrag: Mit Zinsen 
* Leasingvertrag: ist ein Mischvertrag -> Man kann bestehende Verträge mischen 
** Kaufvertrag
** Mietvertrag

=== Vertragsabsicherungen
* Beispiel: Ratenzahlung -> kein Geld mehr -> Man sichert sich den Eigentumsvorbehalt ab 
* Eigentumsvorbehalt: Die Ware gehört so lange mir bis die Ware abbezahlt ist
* Pfand kann auch genommen werden 
* Bürgen -> Ein dritter verpflichtet sich wenn der Schuldner den Vertrag nicht zahlen kann
* Bankgarantie -> Geldbetrag wird bei der Bank hinterlegt -> welches bezogen werden kann 
* Pönale -> Wenn man etwas nicht schafft *rechtzeitig* zu liefern zahlt man -> kann einem ein pauschalierter Schadenersatz bekommen

=== Formvorschriften
* Veträge zunächst sind Formlos -> außer folgende Beispiele:
** Testament
** ins Grundbuch -> Geschenk kaufen -> Notar benötigt 
** ins Firmenbuch -> Notar
** Lehrvertrag -> Unterschrift beider Eltern

=== Vertragserfüllung


=== Leistungsstörunegn
* Beispiel: Handy bei MediaMarkt kaufen -> geht nach 2 Tagen nicht mehr
** Gratanie -> Zeit vom Hersteller frei wählbar
** Gewährleistung (Gerät darf keinen Schaden von Anfang an haben)-> 2-Jahre  Staatlich vorgegeben -> Gesetzlich verpflichtend
*** Bis zu dem ertsen Jahr muss man nichts beweise
*** Ab dem 2ten Jahr muss bewiesen werden, ob etwas kaputt war

* Gewährleistung besteht aus: 
** Reperatur oder
** Austauschen
*** wenn beides nicht mehr möglich ist dann 
** Geldbetrag zurück   

== 2023-06-11

=== Schadensersatzrecht

* 4 Faktoren(Schadensrecht): 
** Verschulden
** Kausalität 
** Schaden 
** Rechtswidrig

Fällt ein Faktor fällt der Schaden weg 

=== Verschulden
* leichte Fahrlässigkeit -> Laptop zufällig herunter geschmissen 
* grobe Fahrlässigkeit -> passiert nicht jedem ->
* vorsätzlich gehandelt: absichtlich was tun oder in Kauf nehmen 

=== Ersatz -> Wann gilt der Schaden
* leichte Fahrlässigkeit:
** Man muss nichts oder einen Teil
* grobe Fahrlässigkeit:
** Man muss alles ersetzen 
* vorsätzlich gehandelt: 
** Man muss den Laptop und die emotionale Schiene Zahlen (Laptop vom Großvater -> 5000€ vom gefühl her)

=== Schadenersatz Schäden
* Sachschaden 
* Körperschaden
* Vermögensschaden
* Schockschaden
* Trauerschaden -> Angehörige
* Emotionaler Schaden

=== Kausalität
Mein Schadensereignis führt direkt zum Schaden 

* Die Kausalkette darf nicht zu lang sein 

* Beispiel: 
** Ein späterer Schaden durch zugefügten Schaden führt zum Schaden

=== Rechtswidrig 
* Deliktischer Schaden
* Vertraglicher Schaden 

=== Mitverschulden 
* Wenn man eine Teilschuld muss man halbieren oder maximal gedrittelt

=== Schadensminderungspflicht 
* Man hat gelegenheit der Unfall zu verhindern -> Man kann den entstandenen Schaden wieder mindern

Schadenersatz ist in Österreich genau 3 Jahre geltend.

---

* Wie wird der Schadensersatz berechnet
** Zuerst geht man zum Arzt -> nachweisen vom Schaden
** Wie Lange dauert der Krankenstand 
** Schadennersatz wird errechnet

== 2023-20-11
=== Buchseite 271)
* https://www.wko.at/gewerberecht/gewaehrleistung-garantie-schadenersatz#heading_Begriffsabgrenzung[ALLES ZUM THEMA]

* Aufischtspflichverletzungen: Eltern haften für ihre Kinder wenn sie Ihre Schuldhaft verletzten
** Nur Schuld wenn die Situation gefährlich ist
** Kind braucht Betreuung bekommt keine 

=== Rechtfertigung für Verschuldung
* Notstandssitutaionen
** Kind im brennenden Auto gefangen 
** Selbstverteidigung
* Geisteskranke und unmündige Haften nicht -> Man versteht nicht was man macht
* Wenn der Geisteskranke Millionär ist zahlt der beeinträchtigte 

=== Gehilfenhaftung 
* Als Unternehmerin hat man als IT Unternehmerin einen Außeneinsatz -> bediensteter fährt zum Auftrag -> ihm passiert ein schaden -> der dort war -> ist ein Verfüllungsgehilfe 
* Erfüllungsgehilfe schädigt andere Vermögenswerte ohne zu arbeiten -> Erfüllungsgehilfe ist schulig -> Unternehmer nicht 

* Besorgungsgehilfenhaftung:
** Untüchtigkeit vom Mitarbeiter ist der einzige weg 
** Erfüllungsgehilfenhaftung
** Als Unternehmerin hat man als IT Unternehmerin einen Außeneinsatz -> bediensteter fährt zum Auftrag -> ihm passiert ein schaden -> der dort war -> ist ein Verfüllungsgehilfe 

* Erfüllungsgehilfe schädigt andere Vermögenswerte ohne zu arbeiten -> Erfüllungsgehilfe ist schulig -> Unternehmer nicht 


* Man möchte trotzdem zu Unternehmer -> Unternehmer zahlt nur dann wenn man als Unternehmer weiß, dass der Erfüllungsgehilfe nicht tüchtig ist. 

== Haftung

* Wohnungseigentümer
** Schmeißt Weihnachtsbaum aus dem Fenster -> Wohnungsinhaber haftet
* Bauwerksinhaber
** Solbald man ein Gebäude hat haftet man für alles

=== Tierhaftung
* Hundebsitzer ist für die Tierverwahrung verantwortlich 
** Ohne Leine -> Schuldig
** Kind geht mit Hund spazieren

=== Gastwirtenhaftung
* Übernachtet man beim Gastwirten und dort dar nichts abhanden kommen. ab 1.100€


== 15.01.2024

=== Komnsumententschutz
* KSCHG -> Konsumentenschutzgesetz
* ECG -> E-Commerece
* FAGG -> Fernabsatz und Auswertsgeschäftegesetz


=== KSCHG
Ist ein zwingendes Recht

* Für Haustürgeschäfte -> (Jemand klopft an die Haustür -> Staubsaugerverkäufe von Tür zu Tür) entwickelt. 
** bis 1975 -> Frau hat nichts zu sagen gehabt -> am Herd gebunden -> Schlüsselgewalt -> Männer zahlen alles

* (Rücktrittsrecht) Rücktritt möglich -> also völlig formlos -> Ich will den Staubsauger nicht -> kann jederzeit zurückgegeben werden
* (Recht des Kleingedruckten) Mit dem Konsumentenschutz wehrt man sich gegen dieses Kleingedruckte

* Schriftlicher Kostenvoranschlag kann wegen dem KSCHG angerechnet werden -> Konsument sieht ihn und kann sich entscheiden -> ja nein
** Verbindlich:
*** Wenn man nicht unverbindlich dazuschreibt -> ist dieser verbindlich
*** Ist ein muss
** Unverbindlich:
*** Wenn eine Reperatur mehr kostet als ausgemacht darf diese maximal um 15% teurer werden -> muss aber dem Konsumenten mitgeteilt werden 




=== ECG

=== FAGG

* Rücktrittsrecht 
** Wer ist für die Kosten für die Rücksendung verantwortlich? -> Der Käufer ist für die Versandkosten der Rücksendung verantwortlich
** Onlinehandel -> man kann ein Produkt innerhalb 14 Tage online zurückgeben (ohne wenn und aber)
** Geschäft -> man kauft ein Produkt in ein Geschäft -> man kann dieses nicht sofort wieder zurückgeben -> Geschäfte können aber auch Rückgabefristen definieren


Steht im Fagg -> Fernabsatzgesetz

Wenn man die Belehrung über den zurücktritt nicht angibt -> Darf der Kunde 1 Jahr lang zurücktreten.

*Fall:* Auswertskundendienst -> Webseite wird gebaut -> Man fährt zum Kunden -> Ist hochzufrieden -> Nachber kauft sich gleich auch den service -> Rücktrittsrecht wird nicht vorgelegt -> Kunde kommt nach einem Jahr drauf: Ich brauche das Produkt nicht -> Kunde darf zurücktreten und muss 1 Jahr nichts blechen

Sonderanfertigungen -> Rücktrittsrecht fällt weg -> ohne Widerrufsbestätigung -> muss man dafür nichts bezahlen



== E-Commerce Gesetz

Gesetz für den Onlinehandel

* E-Commerce regelt die Unternehmerseite um einen soliden Onlinehandel zu garantieren -> Europäische Richtlinie für alle
* Gewerbeberechtigung reich um eine Webseite zu erstellen
* Man will auf der Webseite Baustoffe vertreiben:
** Preisgestaltung muss sichtlich gestaltet werden
*** Deutlichmachung des Preises -> Bevor man auf den bestellen knopf muss ersichtlich sein wie viel der Gesamtbetrag beträgt
** Impressum muss ersichtlich sein -> Wenn nicht verfügbar -> Man muss bis zu 3000 zahlen


Beispiele: 

* Anton bestellt sich im Internet einen Fernseher -> liest sich die AGB's durch -> will sie runterladen -> PDF ist gesperrt

** Unternehmen muss die AGBS zur verfügungstellen -> herunterladbar und ausdruckbar



* Alfred betreibt eine Suchmaschine -> Kinder geben Nationalsozialistische Begriffe ein -> kommen auf so eine seite -> Eltern wollen jemanden zur rechenschaft ziehen 

** Große Suchmac

** Alfred ist nicht zu belangen wenn:

*** die Übermittlung der abgefragten Informationen nicht veranlasst,
*** den Empfänger der abgefragten Informationen nicht auswählt und
*** die abgefragten Informationen weder auswählt noch verändert.


* Xaver kommt auf die Seite von Ludwig -> Ludwig beitet freeware und software -> Xaver tschuat sich die Ware -> stellt diese neu zur verfügung -> Ludwig hat aber mittlerweile auf Raubkopien umgestellt. Jemand will Xaver verurteilen, weil dieser den Link zur verfügung gestellt hat

** Xaver ist nicht zu belangen:
*** Wenn er nicht weiß dass er illegale Inhalte verkauft 
** jedoch haftet er weil es nicht seine inhalte sind


* Siggi macht eine Entdeckung unter einer webseite -> man erwirbt dinge und bekommt sie zugeschickt -> erwirbt eine Stereoanlage. Analge kommt an und kommt kleiner als gedacht an. Sigis Anlage ist zu klein.

** Sigi: widerufsformular fehlt -> 1 Jahr + 14 tage



Katariner hat bei einem Gebrauchtwagenhändler ein Auto gekauft -> Macht einen selbstverschuldeten Unfall -> Will wissen wie viel die herrichtung kostet -> Kriegt eine Rechnung ohne Umsatzsteuer -> Bei der abholung kostet es 750 -> Sie hat es nicht gewusst -> Ihr wurde nichts mitgeteil -> verbindlich für den produzenten