--1
DROP TABLE BUECHER;
DROP TABLE LESER;
DROP TABLE VERLEIH;
DROP TABLE VORMERK;
DROP TABLE STRAFE;


CREATE TABLE BUECHER (
    BuchNr NUMBER CONSTRAINT PK_BuchNr Primary Key,
    Autor VARCHAR(20),
    Titel VARCHAR(50),
    Gruppe CHAR,
    Leihfrist NUMBER
);

CREATE TABLE LESER (
    LeserNr NUMBER CONSTRAINT PK_LeserNrLeser Primary Key,
    Name VARCHAR(20),
    Wohnort VARCHAR(20),
    Eintrittsdatum DATE
);

CREATE TABLE VERLEIH (
    LeserNrVerleih NUMBER CONSTRAINT FK_LeserNrVerleih REFERENCES LESER,
    BuchNrVerleih NUMBER CONSTRAINT FK_BuchNrVerleih REFERENCES BUECHER,
    Ausleihdatum DATE,
    Rueckgabedatum DATE
);

CREATE TABLE VORMERK (
    LeserNrVormerk NUMBER CONSTRAINT FK_LeserNrVormerk REFERENCES LESER,
    BuchNrVormerk NUMBER CONSTRAINT FK_BuchNrVormerk REFERENCES BUECHER,
    ReservFuerDat DATE
);

CREATE TABLE STRAFE (
    LeserNrStrafe NUMBER CONSTRAINT FK_LeserNrStrafe REFERENCES LESER,
    SperreBisDat DATE CONSTRAINT PK_SperreBisDat Primary Key,
    Gebuehr NUMBER
);


--

--2
SELECT BUCHNR, AUTOR, TITEL, VORMERKDATUM FROM BUECHER b FULL OUTER JOIN VORMERK vo WHERE b.BUCHNR = v.BUCHNR; -- TOCHAR(VORMERKDATUM, "Day-Month-YYYY")


--3
SELECT LESERNR, NAME, WOHNORT, COUNT(*) AS ANZAHLBUECHER FROM LESER;


--4
SELECT LESERNR, NAME, WOHNORT, TITEL, RUECKGABE FROM BUECHER b FULL OUTER JOIN VERLEIH ve WHERE b.BUCHNR = ve.BUCHNR < ANY (SELECT TITEL FROM BUECHER WHERE AUTOR = ("GOE" ...)); -- TOCHAR(VORMERKDATUM, "DD-MON-YYYY")


--5
SELECT BUCHNR, AUTOR, TITEL, (RUECKGABEDATUM, RESERVFUERDAT) FROM BUECHER b FULL OUTER JOIN VORMERK vo WHERE b.BUCHNR = vo.BUCHNR;


--6
SELECT LESERNR, NAME, WOHNORT, COUNT(GEBUEHR) FROM STRAFE s FULL OUTER JOIN LESER l WHERE s.LESERNR = l.LESERNR WHERE LESERNR ... GEBUEHR ADD;









