--Adelwöhrer leonie 3AHITM 01

--1.1 RICHTIG -> Ergebnis 3 von P und 1 von S
SELECT VNR,SPARTE from VERTRAG
where VENDE IS NULL;

--1.2 RICHTIG -> Ergebnis 115000
SELECT VSUMME from VERTRAGSHISTORIE
where VNR = 154 AND (TO_CHAR(DATUM_VON,'YYYY-MM-DD') = '2000-06-01');

--1.3 RICHTIG! 1/4 vom Jahr R Monat 12,11,10 -> Ergebnis 154 und 453
SELECT VNR,TO_CHAR(DATUM_VON,'DD.MM.YYYY') from VERTRAGSHISTORIE
where TO_CHAR(DATUM_VON,'YYYY') = 1997 and TO_CHAR(DATUM_VON,'MM') > 9;

--1.4
SELECT VNR from VERTRAG
where VNR in (SELECT VNR from ZAHLUNG where BETRAG = BETRAG);

SELECT VNR from VERTRAG
where VNR in (SELECT VNR from ZAHLUNG where BETRAG = BETRAG);

--1.5
SELECT VNR from ZAHLUNG
where TO_CHAR(ZDATUM,'YYYY') < ANY(SELECT TO_CHAR(ZDATUM,'YYYY') from ZAHLUNG where TO_CHAR(ZDATUM,'YYYY') < 2002)
group by VNR;

--1.6
--Versuch 1
SELECT vg.VNR from VERTRAG vg, VERTRAGSHISTORIE
where VENDE IS NULL AND VSUMME = ALL(SELECT sum(VSUMME) from VERTRAGSHISTORIE)
group by vg.VNR;

--Versuch 2
SELECT VSUMME from VERTRAGSHISTORIE
where VNR = ANY(SELECT VNR from VERTRAG where VENDE IS NULL group by VNR);

--Versuch 3
SELECT VSUMME from VERTRAGSHISTORIE
MINUS
SELECT VSUMME from VERTRAGSHISTORIE,VERTRAG where VENDE is not null;

--Versuch 4
SELECT VNR from VERTRAGSHISTORIE where VNR in (Select VSUMME from VERTRAGSHISTORIE)
MINUS
SELECT VNR from VERTRAGSHISTORIE where VNR in (Select VSUMME from VERTRAGSHISTORIE where )
group by VNR;
