-- 1.1
SELECT COUNT(*) AS "ANZAHL", SPARTE FROM VERTRAG
WHERE VENDE IS NULL
GROUP BY SPARTE;

-- 1.2
SELECT VSUMME FROM VERTRAGSHISTORIE
WHERE
        VNR = 154
  AND DATUM_VON <= TO_DATE('2000-06-03', 'yyyy-mm-dd')
ORDER BY DATUM_VON DESC
-- nur das erste Ergebnis (=> den letzten Stand) anzeigen
    FETCH FIRST 1 ROWS ONLY;

-- 1.3
SELECT VNR, TO_CHAR(VBEGINN, 'dd.mm.yy') AS "VBEGINN" FROM  VERTRAG
WHERE VBEGINN BETWEEN TO_DATE('01.09.1997', 'dd.mm.yyyy') AND TO_DATE('31.12.1997', 'dd.mm.yyyy');

-- 1.4
-- Version 1 - "Minus Chaos"
SELECT VNR FROM VERTRAGSHISTORIE
GROUP BY VNR
MINUS
SELECT VNR FROM VERTRAGSHISTORIE
WHERE DATUM_VON > TO_DATE('31.12.02', 'dd.mm.yy')
MINUS
SELECT VNR FROM VERTRAG
WHERE SPARTE != 'P';

-- Version 2
SELECT VERTRAG.VNR FROM VERTRAG
INNER JOIN VERTRAGSHISTORIE HIST ON VERTRAG.VNR = HIST.VNR
WHERE
    SPARTE = 'P'
    AND DATUM_VON < TO_DATE('31.12.02', 'dd.mm.yy')
GROUP BY VERTRAG.VNR;

-- 1.5          
SELECT V.VNR, SPARTE, TO_CHAR(VBEGINN, 'dd.mm.yy') AS "VBEGINN", VENDE FROM VERTRAG V
 LEFT JOIN ZAHLUNG Z on V.VNR = Z.VNR
WHERE
    VENDE IS NULL
    AND ZDATUM >= ALL(SELECT ZDATUM FROM ZAHLUNG Z2 WHERE V.VNR = Z2.VNR)
    AND (ZDATUM IS NULL OR TO_CHAR(ZDATUM, 'yy') < TO_CHAR(sysdate, 'yy') - 1);

-- 1.6
SELECT VNR, VSUMME
FROM VERTRAGSHISTORIE HIST
WHERE
    DATUM_VON >= ALL(SELECT DATUM_VON FROM VERTRAGSHISTORIE HIST2 WHERE HIST2.VNR = HIST.VNR)
    AND VNR NOT IN (SELECT VNR FROM VERTRAG V WHERE V.VENDE IS NOT NULL)
ORDER BY VNR;