services:
  web:
    container_name: my-nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    container_name: my-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql

  adminer:
    container_name: my-adminer
    image: adminer
    ports:
      - 8090:8080
    
  phpmyadmin: 
    container_name: php-my-admin
    image: phpmyadmin:latest
    ports:
      - 5007:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
    depends_on: 
      - db

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8110:80
    environment:
      WORDPRESS_DB_HOST: my-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html/wp-content

volumes:
  db:
  wordpress:

# wordpress
# wordpress
# wordpress@gmail.com